import type { City, SeasonalData } from './types';

export const cities: City[] = [
  // Top US Cities
  { name: "Los Angeles", state: "CA", population: 3898747, lgbtqIndex: 92, stayArea1: "West Hollywood", stayArea2: "Silver Lake" },
  { name: "New York", state: "NY", population: 8804190, lgbtqIndex: 95, stayArea1: "Chelsea", stayArea2: "Greenwich Village" },
  { name: "Miami", state: "FL", population: 467963, lgbtqIndex: 88, stayArea1: "South Beach", stayArea2: "Wynwood" },
  { name: "Chicago", state: "IL", population: 2746388, lgbtqIndex: 85, stayArea1: "Boystown", stayArea2: "Andersonville" },
  { name: "Dallas", state: "TX", population: 1343573, lgbtqIndex: 78, stayArea1: "Oak Lawn", stayArea2: "Uptown" },
  { name: "Atlanta", state: "GA", population: 498715, lgbtqIndex: 84, stayArea1: "Midtown", stayArea2: "Virginia Highland" },
  { name: "Houston", state: "TX", population: 2304580, lgbtqIndex: 82, stayArea1: "Montrose", stayArea2: "Heights" },
  { name: "Las Vegas", state: "NV", population: 641903, lgbtqIndex: 85, stayArea1: "The Strip", stayArea2: "Downtown" },
  { name: "San Francisco", state: "CA", population: 873965, lgbtqIndex: 98, stayArea1: "Castro District", stayArea2: "Mission District" },
  { name: "Phoenix", state: "AZ", population: 1608139, lgbtqIndex: 75, stayArea1: "Melrose District", stayArea2: "Downtown" },
  { name: "San Diego", state: "CA", population: 1386932, lgbtqIndex: 87, stayArea1: "Hillcrest", stayArea2: "North Park" },
  { name: "Seattle", state: "WA", population: 737015, lgbtqIndex: 91, stayArea1: "Capitol Hill", stayArea2: "Fremont" },
  { name: "Washington", state: "DC", population: 689545, lgbtqIndex: 90, stayArea1: "Dupont Circle", stayArea2: "Logan Circle" },
  { name: "Orlando", state: "FL", population: 307573, lgbtqIndex: 86, stayArea1: "Downtown", stayArea2: "Lake Nona" },
  { name: "Denver", state: "CO", population: 715522, lgbtqIndex: 86, stayArea1: "Capitol Hill", stayArea2: "RiNo" },
  { name: "Austin", state: "TX", population: 961855, lgbtqIndex: 87, stayArea1: "Downtown", stayArea2: "South Congress" },
  { name: "Portland", state: "OR", population: 652503, lgbtqIndex: 90, stayArea1: "Pearl District", stayArea2: "Hawthorne" },
  { name: "Tampa", state: "FL", population: 384959, lgbtqIndex: 83, stayArea1: "Ybor City", stayArea2: "Downtown" },
  { name: "San Jose", state: "CA", population: 1013240, lgbtqIndex: 80, stayArea1: "Downtown", stayArea2: "Willow Glen" },
  { name: "Philadelphia", state: "PA", population: 1603797, lgbtqIndex: 80, stayArea1: "Gayborhood", stayArea2: "Midtown Village" },

  // US State Capitals
  { name: "Montgomery", state: "AL", population: 200603, lgbtqIndex: 60, stayArea1: "Downtown", stayArea2: "Cloverdale" },
  { name: "Juneau", state: "AK", population: 32255, lgbtqIndex: 70, stayArea1: "Downtown", stayArea2: "Mendenhall Valley" },
  // Phoenix is already in top cities
  { name: "Little Rock", state: "AR", population: 202591, lgbtqIndex: 65, stayArea1: "River Market", stayArea2: "The Heights" },
  { name: "Sacramento", state: "CA", population: 524943, lgbtqIndex: 85, stayArea1: "Midtown", stayArea2: "Lavender Heights" },
  // Denver is already in top cities
  { name: "Hartford", state: "CT", population: 121054, lgbtqIndex: 78, stayArea1: "Downtown", stayArea2: "West End" },
  { name: "Dover", state: "DE", population: 39403, lgbtqIndex: 70, stayArea1: "Downtown", stayArea2: "The Green" },
  { name: "Tallahassee", state: "FL", population: 196169, lgbtqIndex: 75, stayArea1: "Midtown", stayArea2: "College Town" },
  // Atlanta is already in top cities
  { name: "Honolulu", state: "HI", population: 350964, lgbtqIndex: 88, stayArea1: "Waikiki", stayArea2: "Kaka'ako" },
  { name: "Boise", state: "ID", population: 235684, lgbtqIndex: 77, stayArea1: "Downtown", stayArea2: "North End" },
  { name: "Springfield", state: "IL", population: 114394, lgbtqIndex: 72, stayArea1: "Downtown", stayArea2: "Old State Capitol" },
  { name: "Indianapolis", state: "IN", population: 887642, lgbtqIndex: 79, stayArea1: "Mass Ave", stayArea2: "Broad Ripple" },
  { name: "Des Moines", state: "IA", population: 214133, lgbtqIndex: 76, stayArea1: "East Village", stayArea2: "Downtown" },
  { name: "Topeka", state: "KS", population: 126587, lgbtqIndex: 68, stayArea1: "Downtown", stayArea2: "NOTO Arts District" },
  { name: "Frankfort", state: "KY", population: 28602, lgbtqIndex: 67, stayArea1: "Downtown", stayArea2: "South Frankfort" },
  { name: "Baton Rouge", state: "LA", population: 227470, lgbtqIndex: 70, stayArea1: "Downtown", stayArea2: "Mid City" },
  { name: "Augusta", state: "ME", population: 19136, lgbtqIndex: 75, stayArea1: "Downtown", stayArea2: "Water Street" },
  { name: "Annapolis", state: "MD", population: 40812, lgbtqIndex: 80, stayArea1: "Historic District", stayArea2: "Eastport" },
  { name: "Boston", state: "MA", population: 675647, lgbtqIndex: 89, stayArea1: "South End", stayArea2: "Back Bay" },
  { name: "Lansing", state: "MI", population: 112644, lgbtqIndex: 74, stayArea1: "Old Town", stayArea2: "Downtown" },
  { name: "St. Paul", state: "MN", population: 311527, lgbtqIndex: 82, stayArea1: "Lowertown", stayArea2: "Grand Avenue" },
  { name: "Jackson", state: "MS", population: 153701, lgbtqIndex: 62, stayArea1: "Fondren", stayArea2: "Downtown" },
  { name: "Jefferson City", state: "MO", population: 43228, lgbtqIndex: 69, stayArea1: "Downtown", stayArea2: "Old Munichburg" },
  { name: "Helena", state: "MT", population: 32091, lgbtqIndex: 73, stayArea1: "Last Chance Gulch", stayArea2: "Mansion District" },
  { name: "Lincoln", state: "NE", population: 291082, lgbtqIndex: 75, stayArea1: "Haymarket", stayArea2: "Downtown" },
  { name: "Carson City", state: "NV", population: 58639, lgbtqIndex: 71, stayArea1: "Historic District", stayArea2: "Downtown" },
  { name: "Concord", state: "NH", population: 43976, lgbtqIndex: 79, stayArea1: "Main Street", stayArea2: "South End" },
  { name: "Trenton", state: "NJ", population: 90871, lgbtqIndex: 74, stayArea1: "Downtown", stayArea2: "Mill Hill" },
  { name: "Santa Fe", state: "NM", population: 87505, lgbtqIndex: 88, stayArea1: "The Plaza", stayArea2: "Canyon Road" },
  { name: "Albany", state: "NY", population: 99224, lgbtqIndex: 81, stayArea1: "Center Square", stayArea2: "Lark Street" },
  { name: "Raleigh", state: "NC", population: 467665, lgbtqIndex: 80, stayArea1: "Warehouse District", stayArea2: "Glenwood South" },
  { name: "Bismarck", state: "ND", population: 73622, lgbtqIndex: 70, stayArea1: "Downtown", stayArea2: "Cathedral District" },
  { name: "Columbus", state: "OH", population: 905748, lgbtqIndex: 83, stayArea1: "Short North", stayArea2: "German Village" },
  { name: "Oklahoma City", state: "OK", population: 681054, lgbtqIndex: 72, stayArea1: "Paseo Arts District", stayArea2: "Plaza District" },
  { name: "Salem", state: "OR", population: 175535, lgbtqIndex: 80, stayArea1: "Downtown", stayArea2: "West Salem" },
  { name: "Harrisburg", state: "PA", population: 50099, lgbtqIndex: 76, stayArea1: "Midtown", stayArea2: "Downtown" },
  { name: "Providence", state: "RI", population: 190934, lgbtqIndex: 85, stayArea1: "Downtown", stayArea2: "Federal Hill" },
  { name: "Columbia", state: "SC", population: 136632, lgbtqIndex: 73, stayArea1: "The Vista", stayArea2: "Main Street" },
  { name: "Pierre", state: "SD", population: 14091, lgbtqIndex: 65, stayArea1: "Downtown", stayArea2: "Historic District" },
  { name: "Nashville", state: "TN", population: 689447, lgbtqIndex: 78, stayArea1: "The Gulch", stayArea2: "East Nashville" },
  // Austin is already in top cities
  { name: "Salt Lake City", state: "UT", population: 199723, lgbtqIndex: 84, stayArea1: "Downtown", stayArea2: "9th and 9th" },
  { name: "Montpelier", state: "VT", population: 8074, lgbtqIndex: 82, stayArea1: "Downtown", stayArea2: "Main Street" },
  { name: "Richmond", state: "VA", population: 226649, lgbtqIndex: 79, stayArea1: "Scott's Addition", stayArea2: "Carytown" },
  { name: "Olympia", state: "WA", population: 55605, lgbtqIndex: 83, stayArea1: "Downtown", stayArea2: "Westside" },
  { name: "Charleston", state: "WV", population: 48864, lgbtqIndex: 68, stayArea1: "Downtown", stayArea2: "East End" },
  { name: "Madison", state: "WI", population: 269840, lgbtqIndex: 86, stayArea1: "Isthmus", stayArea2: "Willy Street" },
  { name: "Cheyenne", state: "WY", population: 65132, lgbtqIndex: 67, stayArea1: "Downtown", stayArea2: "Historic District" },
];

export const seasonalData: SeasonalData = {
  0: { name: "January", optimalDays: "5-7", multiplier: 0.85 },
  1: { name: "February", optimalDays: "3-5", multiplier: 1.1 },
  2: { name: "March", optimalDays: "5-7", multiplier: 1.15 },
  3: { name: "April", optimalDays: "4-6", multiplier: 0.95 },
  4: { name: "May", optimalDays: "6-8", multiplier: 1.2 },
  5: { name: "June", optimalDays: "7-10", multiplier: 1.5 },
  6: { name: "July", optimalDays: "5-7", multiplier: 1.25 },
  7: { name: "August", optimalDays: "5-7", multiplier: 1.15 },
  8: { name: "September", optimalDays: "4-6", multiplier: 0.9 },
  9: { name: "October", optimalDays: "5-7", multiplier: 1.0 },
  10: { name: "November", optimalDays: "3-5", multiplier: 0.8 },
  11: { name: "December", optimalDays: "4-6", multiplier: 1.2 }
};
