
export const currentKeywords: string[] = [
    "gay massage",
    "male massage",
    "gay massage near me",
    "male massage therapist near me",
    "massage for men",
    "male massage therapist",
    "male to male massage",
    "male massage near me",
    "massage near me for men",
    "gay massage therapist near me",
    "gay masseur near me",
    "gay masseur",
    "m4m massage near me",
    "gay massage therapist",
    "rentmasseur",
    "masseurfinder",
    "male spa massage",
    "male to male body massage near me",
    "male massage spa near me",
    "lgbtq massage near me",
];

export const trendingKeywords: string[] = [
    "male to male massage therapist near me",
    "lgbtq friendly massage near me",
    "gay massage spa near me",
    "gay male massage therapist",
    "body massage for men near me",
    "deep tissue massage for men",
    "male massage at home",
    "traveling male massage therapist",
    "mobile male massage service",
    "asmr male massage",
    "intimate male massage",
    "gay massage for couples",
    "male spa near me",
    "med spa for men",
    "men’s facial treatment near me",
    "men’s facial spa near me",
    "male foot massage and pedicure near me",
    "male lmt",
    "muscle guy massage",
    "lgbtq massage therapy",
];
